spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.application.name=spring-backend-auth
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=auth

auth-server.frontend.client-id=${AUTH_SERVER_FRONTEND_CLIENT_ID}
auth-server.frontend.origin=${AUTH_SERVER_FRONTEND_ORIGIN}
auth-server.platform.allowed-origins=${AUTH_SERVER_PLATFORM_ALLOWED_ORIGINS}
auth-server.issuer=${AUTH_SERVER_ISSUER}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
stripe.secret-key = ${STRIPE_SECRET_KEY}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.token.pepper-base64=${SECURITY_TOKEN_PEPPER_BASE64}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:stripeWebhookSecret}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-exception=false
